MB-26226 Fix broken checkout caused by Magento 2.4.7-p1 update
magebitcom/leanpay-integration pull request #141
Opened 2024-08-16 08:40 UTC by AijaMage

2024-08-21 04:51 UTC, IvansMuzicenkoMagebit approved these changes

2024-08-22 07:29 UTC, EmilsM requested changes

2024-08-22 07:29 UTC, EmilsM commented on etc/config.xml
> +        <csp>
add to csp_whitelist.xml instead of this

2024-08-29 14:10 UTC, EmilsM approved these changes

2024-08-29 14:10 UTC, merged